### ISSUE TITLE
[Feature]  Request support for termux-app

### ISSUE THREAD

**Issue by 0x5c0f** [ekzhang/sshx#103] opened 2024-11-26 07:26 UTC
希望能支持 [termux](https://github.com/termux/termux-app) 运行 , 目前运行报告以下错误   

I hope to support [termux](https://github.com/termux/termux-app) running, currently the following error is reported when running 

```bash
~ $ sshx  
2024-11-26T07:16:17.347212Z ERROR sshx: transport error

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again
~ $
```

**Comment by ekzhang** [comment] 2024-11-26 19:40
Duplicate of #102.

**Closed by ekzhang** 2024-11-26 19:40 UTC
