### ISSUE TITLE
[BUG] chat form input tries to autocomplete credit card info

### ISSUE THREAD

**Issue by cgsdev0** [ekzhang/sshx#94] opened 2024-09-05 22:13 UTC
for whatever reason, the text input for the chat tries to autocomplete my credit card info in chrome

it should probably not do that

i'm actually not sure what's causing this exactly, seems very odd

**Comment by ekzhang** [comment] 2024-09-07 21:54
Operating system, Chrome version, and what computer?

**Comment by cgsdev0** [comment] 2024-09-09 16:04
it was on windows 10, latest chrome

don't have exact version info available at the moment, but I'll update when i do

requires having a credit card number saved in chrome, and probably not reproducible on localhost (iirc, chrome requires https:// for credit card auto fill)

**Comment by ekzhang** [comment] 2024-09-09 16:46
Thanks. I can reproduce it for the "Your name" input on Chrome in Incognito on macOS.

Unfortunately there doesn't seem to be a good solution. I did some searching, and adding `autocomplete="one-time-code"` is the only thing that works for me. This is not an acceptable solution though since it's really specific behavior, and they might interpret this semantically in a future browser version.

Closing until Chrome offers a better solution for disabling autocomplete.

**Closed** 2024-09-09 16:47 UTC
