### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by Spartan09** [ekzhang/sshx#64] opened 2024-01-01 07:58 UTC
<img width="865" alt="image" src="https://github.com/ekzhang/sshx/assets/31277910/5c1907fe-3539-4125-b434-aff54c325194">
Error

```
2024-01-01T07:55:37.418583Z ERROR sshx: status: PermissionDenied, message: "grpc-status header missing, mapped from HTTP status code 403", details: [], metadata: MetadataMap { headers: {"date": "Mon, 01 Jan 2024 07:55:38 GMT", "cache-control": "private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0", "expires": "Thu, 01 Jan 1970 00:00:01 GMT", "report-to": "{\"endpoints\":[{\"url\":\"https:\/\/a.nel.cloudflare.com\/report\/v3?s=I5MYTyX%2FD%2BkCv26TnLAykfds6I5Ljxr4QqJtlwguZKl9W4JuVqCMV5fCKoFWYMNI3irudiRfJsQMWTzYIwU56f7qNeiLrcIfiXXJs92571t9UgBBRfPIeCik\"}],\"group\":\"cf-nel\",\"max_age\":604800}", "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", "vary": "Accept-Encoding", "server": "cloudflare", "cf-ray": "83e9337c3958f425-BOM", "alt-svc": "h3=\":443\"; ma=86400"} }
```

**Comment by ekzhang** [comment] 2024-01-01 19:45
Hey, thanks for the report. It looks like there's some issue where Cloudflare in front of sshx.io is providing a 403 status code. I haven't seen this before, are you possibly using a Cloudflare client proxy or VPN somewhere?

It might help to try running some commands like:

```bash
dig sshx.io
dig @1.1.1.1 sshx.io
ping sshx.io
curl -i https://sshx.io
```

**Comment by ekzhang** [comment] 2024-01-02 16:54
Closing due to lack of details, unable to reproduce.

**Closed by ekzhang** 2024-01-02 16:54 UTC

**Comment by Spartan09** [comment] 2024-01-04 02:31
I built it from source, and it turns out I was missing the protobuf-compiler which I installed with apt-get and now it's working perfectly fine!
The curl script didn't warn me though it seems.

**Comment by ekzhang** [comment] 2024-01-04 04:16
Thanks for the extra details.

**Comment by Spartan09** [comment] 2024-01-05 07:22
I was kind of stuck in tutorial hell regarding learning Rust, so I was hoping, if you could point me in the general direction of trying to understand this codebase

**Comment by ekzhang** [comment] 2024-01-05 17:50
Sure, why don't you read [the book](https://doc.rust-lang.org/book/) and then we can talk after you're more familiar with Rust?

**Comment by Spartan09** [comment] 2024-01-08 07:48
Hi, sorry for the late reply, I have read the book till the smart pointers part.
