### ISSUE TITLE
[Bug]: atuin ctrl+r doesn't work inside sshx.io

### ISSUE THREAD

**Issue by luochen1990** [ekzhang/sshx#100] opened 2024-09-13 07:55 UTC
Details is described here:   https://github.com/atuinsh/atuin/issues/2385

**Comment by ekzhang** [comment] 2024-09-14 02:00
Replied in the thread

**Comment by ekzhang** [comment] 2024-09-14 02:03
Duplicate of #60.

**Closed** 2024-09-14 02:03 UTC
